### ISSUE TITLE
URL fix

### ISSUE THREAD

**Issue by calvinkw1** [wdi-sf-jan/notes#1]
@tlicata Heads up, the URL for "The Birth of Standard Error" doesn't seem to be working properly.  The URL in there is:

http://spinellis.gr/blog/20131211/

It seems it only works if the URL is the complete one, with the "www.":

http://www.spinellis.gr/blog/20131211/

**Comment by tlicata** [comment]
@calvinkw1 thanks for the heads up.  should be fixed in d078fd3b923f1027b78beab91edb102cc79c76ce
